# Changes here will be overwritten by Copier
_src_path: /tmp/43d30c5f-a6c1-4a29-9bfb-6e2f9586f77e_step-fetch-base-6ePgUB/template
host: github.com
owner: super-awesome-org
projectName: ewq
pythonVersion: 3
repo: demo-repo-12323434343
